wandb_version: 1

balance:
  value: true
e_lr:
  value: 0.0001
encoder_hidden_dim:
  value: 24
encoder_n_layers:
  value: 3
post_hoc_h_size:
  value: 64
post_hoc_lr:
  value: 1.0e-05
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.0001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.31622388253089717
viewmaker_hidden_dim:
  value: 64
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.06660883520307921
viewmaker_loss_weight:
  value: 0.5433478211026803
viewmaker_n_head:
  value: 2
viewmaker_n_layers:
  value: 3
