wandb_version: 1

balance:
  value: true
e_lr:
  value: 0.001
encoder_hidden_dim:
  value: 24
encoder_n_layers:
  value: 2
post_hoc_h_size:
  value: 32
post_hoc_lr:
  value: 1.0e-05
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.12185375660841148
viewmaker_hidden_dim:
  value: 32
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.0629056334010167
viewmaker_loss_weight:
  value: 0.2838777168329643
viewmaker_n_head:
  value: 1
viewmaker_n_layers:
  value: 2
