wandb_version: 1

balance:
  value: true
e_lr:
  value: 0.0001
encoder_hidden_dim:
  value: 64
encoder_n_layers:
  value: 4
post_hoc_h_size:
  value: 24
post_hoc_lr:
  value: 0.001
post_hoc_n_layers:
  value: 4
v_lr:
  value: 0.0001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.4012933981620733
viewmaker_hidden_dim:
  value: 24
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.08319424471130957
viewmaker_loss_weight:
  value: 0.27709131027068495
viewmaker_n_head:
  value: 2
viewmaker_n_layers:
  value: 2
