wandb_version: 1

balance:
  value: true
e_lr:
  value: 1.0e-05
encoder_hidden_dim:
  value: 32
encoder_n_layers:
  value: 3
post_hoc_h_size:
  value: 64
post_hoc_lr:
  value: 0.0001
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.08063201194809523
viewmaker_hidden_dim:
  value: 64
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.032679809069002405
viewmaker_loss_weight:
  value: 0.4548966166454598
viewmaker_n_head:
  value: 1
viewmaker_n_layers:
  value: 4
