wandb_version: 1

balance:
  value: true
e_lr:
  value: 1.0e-05
encoder_hidden_dim:
  value: 24
encoder_n_layers:
  value: 2
post_hoc_h_size:
  value: 64
post_hoc_lr:
  value: 0.0001
post_hoc_n_layers:
  value: 4
v_lr:
  value: 1.0e-05
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.25386378414184824
viewmaker_hidden_dim:
  value: 64
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.03357707773697938
viewmaker_loss_weight:
  value: 0.6167398408925424
viewmaker_n_head:
  value: 2
viewmaker_n_layers:
  value: 3
