wandb_version: 1

balance:
  value: false
e_lr:
  value: 1.0e-05
encoder_hidden_dim:
  value: 64
encoder_n_layers:
  value: 4
post_hoc_h_size:
  value: 64
post_hoc_lr:
  value: 0.0001
post_hoc_n_layers:
  value: 4
v_lr:
  value: 1.0e-05
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.17235160328157426
viewmaker_hidden_dim:
  value: 24
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.04836625411137547
viewmaker_loss_weight:
  value: 0.4344680322377808
viewmaker_n_head:
  value: 1
viewmaker_n_layers:
  value: 4
