wandb_version: 1

balance:
  value: false
e_lr:
  value: 1.0e-05
encoder_hidden_dim:
  value: 24
encoder_n_layers:
  value: 2
post_hoc_h_size:
  value: 32
post_hoc_lr:
  value: 0.001
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.411275429173203
viewmaker_hidden_dim:
  value: 24
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.0910115764792556
viewmaker_loss_weight:
  value: 0.6783734658680738
viewmaker_n_head:
  value: 2
viewmaker_n_layers:
  value: 3
