wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711592760.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.13
      5: 0.16.4
      8:
      - 5
      13: darwin-x86_64
balance:
  desc: null
  value: true
e_lr:
  desc: null
  value: 0.0001
encoder_hidden_dim:
  desc: null
  value: 64
encoder_n_layers:
  desc: null
  value: 4
post_hoc_h_size:
  desc: null
  value: 24
post_hoc_lr:
  desc: null
  value: 0.001
post_hoc_n_layers:
  desc: null
  value: 4
v_lr:
  desc: null
  value: 0.0001
viewmaker_activation:
  desc: null
  value: relu
viewmaker_distortion_budget:
  desc: null
  value: 0.4012933981620733
viewmaker_hidden_dim:
  desc: null
  value: 24
viewmaker_layer_type:
  desc: null
  value: lstm
viewmaker_loss_t:
  desc: null
  value: 0.08319424471130957
viewmaker_loss_weight:
  desc: null
  value: 0.27709131027068495
viewmaker_n_head:
  desc: null
  value: 2
viewmaker_n_layers:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 1
t:
  desc: null
  value: 0.08319424471130957
v_loss_weight:
  desc: null
  value: 0.27709131027068495
viewmaker:
  desc: null
  value: "TimeSeriesViewMaker(\n  (activation): ReLU()\n  (net): Sequential(\n   \
    \ (0): LSTM(13, 24, num_layers=2, batch_first=True)\n    (1): extract_tensor()\n\
    \    (2): LayerNorm((24,), eps=1e-05, elementwise_affine=True)\n    (3): ReLU()\n\
    \    (4): Linear(in_features=24, out_features=12, bias=True)\n    (5): LayerNorm((12,),\
    \ eps=1e-05, elementwise_affine=True)\n  )\n)"
encoder:
  desc: null
  value: "PlasmaViewEncoderLSTM(\n  (lstm): LSTM(12, 64, num_layers=4, batch_first=True)\n\
    \  (out): Sequential(\n    (0): Linear(in_features=64, out_features=12, bias=True)\n\
    \    (1): ReLU()\n    (2): Linear(in_features=12, out_features=12, bias=True)\n\
    \  )\n)"
train_dataset:
  desc: null
  value: <data.PlasmaDataset object at 0x7fdac99e7f40>
val_dataset:
  desc: null
  value: <data.PlasmaDataset object at 0x7fdad711d150>
collate_fn:
  desc: null
  value: data.viewmaker_collate_fn
included_machines:
  desc: null
  value:
  - cmod
  - east
  - d3d
viewmaker_batch_size:
  desc: null
  value: 1
viewmaker_num_epochs:
  desc: null
  value: 10
post_hoc_num_epochs:
  desc: null
  value: 10
post_hoc_save_metric:
  desc: null
  value: accuracy
post_hoc_batch_size:
  desc: null
  value: 1
