wandb_version: 1

balance:
  value: false
e_lr:
  value: 0.001
encoder_hidden_dim:
  value: 64
encoder_n_layers:
  value: 4
post_hoc_h_size:
  value: 64
post_hoc_lr:
  value: 0.001
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.0001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.1225630316085424
viewmaker_hidden_dim:
  value: 24
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.048433187437096334
viewmaker_loss_weight:
  value: 0.26269736714209
viewmaker_n_head:
  value: 2
viewmaker_n_layers:
  value: 2
