wandb_version: 1

balance:
  value: true
e_lr:
  value: 0.001
encoder_hidden_dim:
  value: 24
encoder_n_layers:
  value: 3
post_hoc_h_size:
  value: 24
post_hoc_lr:
  value: 0.001
post_hoc_n_layers:
  value: 2
v_lr:
  value: 0.0001
viewmaker_activation:
  value: relu
viewmaker_distortion_budget:
  value: 0.11381982895742628
viewmaker_hidden_dim:
  value: 24
viewmaker_layer_type:
  value: lstm
viewmaker_loss_t:
  value: 0.031491076172065036
viewmaker_loss_weight:
  value: 0.28728532892223974
viewmaker_n_head:
  value: 1
viewmaker_n_layers:
  value: 2
